//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IspitiNRAKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ispit()
        {
            this.IspitSkupPitanjas = new HashSet<IspitSkupPitanja>();
            this.IspitGrupas = new HashSet<IspitGrupa>();
            this.Rezultats = new HashSet<Rezultat>();
        }
    
        public int IdIspit { get; set; }
        public string Naziv { get; set; }
        public System.DateTime Datum { get; set; }
        public int Trajanje { get; set; }
        public int UvjetProlaza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IspitSkupPitanja> IspitSkupPitanjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IspitGrupa> IspitGrupas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezultat> Rezultats { get; set; }
    }
}
