//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IspitiNRAKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IspitSkupPitanja
    {
        public int IdIspitSkupPitanja { get; set; }
        public int UvjetProlaza { get; set; }
        public int BrojPitanja { get; set; }
        public int IspitId { get; set; }
        public int SkupPitanjaId { get; set; }
    
        public virtual Ispit Ispit { get; set; }
        public virtual SkupPitanja SkupPitanja { get; set; }
    }
}
