//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IspitiNRAKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.GrupaKorisniks = new HashSet<GrupaKorisnik>();
            this.Rezultats = new HashSet<Rezultat>();
        }
    
        public int IdKorisnik { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string OIB { get; set; }
        public string Telefon { get; set; }
        public string Zanimanje { get; set; }
        public int SpolId { get; set; }
        public int StrucnaSpremaId { get; set; }
        public int KompanijaId { get; set; }
    
        public virtual Kompanija Kompanija { get; set; }
        public virtual Spol Spol { get; set; }
        public virtual StrucnaSprema StrucnaSprema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupaKorisnik> GrupaKorisniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezultat> Rezultats { get; set; }
    }
}
