//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IspitiNRAKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovor
    {
        public int IdOdgovor { get; set; }
        public string Tekst { get; set; }
        public int Tocno { get; set; }
        public int PitanjeId { get; set; }
    
        public virtual Pitanje Pitanje { get; set; }
    }
}
