//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IspitiNRAKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultat
    {
        public int IdRezultat { get; set; }
        public System.DateTime Vrijeme { get; set; }
        public int Prolaz { get; set; }
        public int BrojBodova { get; set; }
        public decimal Postotak { get; set; }
        public int KorisnikId { get; set; }
        public int IspitId { get; set; }
    
        public virtual Ispit Ispit { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
